name: Lint CS-Fixer

on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: "CS-Fixer"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/mesilov/bitrix24-php-lib:php-cli
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: composer update --no-interaction --no-progress --no-suggest

      - name: "CS-Fixer"
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

      - name: "is CS-Fixer check succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ CS-Fixer check pass, congratulations!'

      - name: "is CS-Fixer check failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ CS-Fixer check failed (╯°益°)╯彡┻━┻'
