name: "Unit tests"

on:
  push:
  pull_request:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress"

jobs:
  tests:
    name: "PHPUnit tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/mesilov/bitrix24-php-lib:php-cli
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          composer update ${{ env.COMPOSER_FLAGS }}

      - name: "run unit tests"
        run: php vendor/bin/phpunit --testsuite=unit_tests --display-warnings --testdox

      - name: "is unit tests tests succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ unit tests pass, congratulations!'

      - name: "is unit tests tests failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ unit tests tests failed (╯°益°)╯彡┻━┻'
